### PR TITLE
[FIX] - adding preventDefault to handleClear

### PR DESCRIPTION
**Pull request by yuvalshim**
When using Multiple select in form (e.g I used with react-final-form) when clicking on clear search it submit the form.

### CODE REVIEW

**Comment by harshzalavadiya** [comment]
@yuvalshim

Thanks for pointing out issue,

Instead of `e.preventDefault()` adding `<button type="button"/>` should fix form submit issue,
https://github.com/harshzalavadiya/react-multi-select-component/blob/master/src/select-panel/index.tsx#L191

will it be possible to for you to make this change?

**Comment by yuvalshim** [comment]
Np

**Comment by yuvalshim** [comment]
Done

**Comment by harshzalavadiya** [comment]
@yuvalshim Thanks
Released v3.0.5

**Comment by yuvalshim** [comment]
> @yuvalshim Thanks
> Released v3.0.5

You welcome.
Expect some more improvements 😉

**Pull request merged**
