### PR TITLE
Feature/debounce search

### PR DESCRIPTION
**Pull request by Kannndev**
Added debounce for search.
Added 2 new props debounceSearch(default = false) and debounceDuration(default = 500).

### CODE REVIEW

**Comment by Kannndev** [comment]
PR for #135

**Comment by harshzalavadiya** [comment]
@Kannndev, looks great on a second thought having debounce enabled by default might be better,

That way We can remove non-debounced implementation so bundle will be bit lighter + they can put 0 if anyone wants to disable this forcefully

What are your thoughts?

This pr is accepted anyway so if you are occupied I'll be happy to do this while merging all of this next week

And once again thank you for your contribution 🙂

**Comment by Kannndev** [comment]
@harshzalavadiya Make sense to be enabled by default. I will make the required changes.

**Comment by Kannndev** [comment]
@harshzalavadiya Have enabled debounce by default and changed duration to 300.

**Pull request merged**
