### PR TITLE
New field feature enable in multi select when search text doesn't match any option

### PR DESCRIPTION
**Pull request by jorge-cob**
When search criteria does not match any option, a feature can be enabled that will show a button allowing to handle a given function. In the Storybook's example the function passed will set a new state with the given item. 

PR-MultiSelect

- In case _enableNewFields_  is passed as prop, a button will render instead of the _No option_ list item. 
-  _onNewField_ should be given a function that will be called with the search text as parameter.

Might be interesting to even allow customization of the icon and the label.

### CODE REVIEW

**Comment by harshzalavadiya** [comment]
@jorge-cob Thank you for the PR however few points

- instead of calling this `enableNewFields` we can think of it as react-select's `isCreatable`  https://react-select.com/creatable#creatable
- instead of rendering button we can have just simple list saying `Create ${newItem}`
- Also this option should be enabled if passed via prop (not only when there are no options)

**Comment by jorge-cob** [comment]
@harshzalavadiya  thanks for the feedback. 

Here a list of changes made to original PR:

- _enableNewFields_ is now named _isCreatable_ following https://react-select.com/creatable#creatable .
- List item is rendered instead of button when no options are available.
- When adding a new field, it gets automatically selected following https://react-select.com/creatable#creatable behaviour.

**Comment by harshzalavadiya** [comment]
@jorge-cob I have made few changes and added docs but I'm not able to push the changes into this PR, can you enable allow edit from maintainers option?

**Comment by jorge-cob** [comment]
@harshzalavadiya edits by maintainers was already enabled. Maybe it's something else?

**Comment by harshzalavadiya** [comment]
@jorge-cob thanks for checking out, no issues, I'll merge this with another local branch `feat-creatable` and then apply patch on top of that so that should work as expected

**Comment by harshzalavadiya** [comment]
released `v4.0.3` thank you for the PR :)

**Pull request merged**
